# https://gohugo.io/hosting-and-deployment/hosting-on-github/
baseURL = "https://juanlufont.github.io"
languageCode = "es"
title = "notas.txt"
theme = "PaperMod"
publishDir = "./public"

[params]
mainSections = ["post", "posts"]
